apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: {{ .Values.storage.storageClass }}

  resources:
    requests:
      storage: {{ .Values.storage.size }}