replicaCount: 1
namespace: testin
image:
  repository: databasus/databasus
  tag: v3.49.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

storage:
  enabled: true
  storageClass: microk8s-hostpath     # o microk8s-hostpath
  size: 5Gi

ingress:
  enabled: true
  className: nginx

  host: databasus.bata.local

  tls: false

resources:
  requests:
    cpu: 250m
    memory: 512Mi

  limits:
    cpu: 1
    memory: 2Gi
