appName: testin
replicaCount: 1
namespace: testin
image:
  name: jeniel/testindata
  tag: dc61932-prod
host:
  #  name: hisbook.bata.local
  name: 192.168.1.184.nip.io
onPrem: true
vite:
  apiUrl: ""
  apiUploadingService: ""
  minioEndpoint: ""
  hospitalName: ""
  hospitalSubname: ""
