apiVersion: batch/v1
kind: CronJob
metadata:
  name: hisd3mk2-roomchargingcron
  namespace: {{ .Values.namespace }}
spec:
  schedule: "0 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hisd3mk2-roomchargingcron
              image: albertoclarit/hisd3base:1.0.3
              imagePullPolicy: IfNotPresent
              command:
                - curl
                - -v
                - --user
                - "{{ .Values.auth.username }}:{{ .Values.auth.password }}"
                - -X
                - POST
                - "https://{{ .Values.host.name }}/api/autochargeRooms"
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hisd3mk2-closingopdcron
  namespace: {{ .Values.namespace }}
spec:
  schedule: "0 14 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hisd3mk2-closingopdcron
              image: albertoclarit/hisd3base:1.0.3
              imagePullPolicy: IfNotPresent
              command:
                - curl
                - -v
                - --user
                - "{{ .Values.auth.username }}:{{ .Values.auth.password }}"
                - -X
                - POST
                - "https://{{ .Values.host.name}}/api/autoCloseOPD"
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hisd3mk2-cleannotification
  namespace: {{ .Values.namespace }}
spec:
  schedule: "0 14 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hisd3mk2-cleannotification
              image: albertoclarit/hisd3base:1.0.3
              imagePullPolicy: IfNotPresent
              command:
                - curl
                - -v
                - --user
                - "{{ .Values.auth.username }}:{{ .Values.auth.password }}"
                - -X
                - POST
                - "https://{{ .Values.host.name }}/api/cleanNotifications"
          restartPolicy: OnFailure
