{{- if .Values.singlenode }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      imagePullSecrets:
        - name: {{.Values.appName }}-secret
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: public/ready
              port: 8080
            initialDelaySeconds: 10     # Wait 5s before first check
            periodSeconds: 10          # Check every 10s
            timeoutSeconds: 2          # Fail if no response in 2s
            failureThreshold: 3        # Mark unready after 3 failures
            successThreshold: 1        # One success to mark ready
          args:
            - -Djava.awt.headless=true
            - --spring.profiles.active=prod
            # - --spring.datasource.url=jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.database }}?sslmode=require
            - --spring.datasource.serverName={{ .Values.database.host }}
            - --spring.datasource.port={{ .Values.database.port }}
            - --spring.datasource.username={{ .Values.database.username }}
            - --spring.datasource.password={{ .Values.database.password }}
            - --spring.datasource.databaseName={{ .Values.database.database }}
            - --connect.url={{ .Values.host.connect }}
            - --minio.url={{ .Values.minio.url }}
            - --minio.accessKey={{ .Values.minio.accessKey }}
            - --minio.secretKey={{ .Values.minio.secretKey }}
            - --minio.bucketName={{ .Values.minio.bucketName }}
            - --hospitalconfig.storageProvider={{ .Values.storage.provider }}
            - --hospitalconfig.alias={{ .Values.hospitalconfig.alias }}
            - --hospitalconfig.isgovernment={{ .Values.hospitalconfig.isgovernment }}
            - --hospitalconfig.coa.version={{ .Values.hospitalconfig.coa.version }}
            - --biometric_middleware.url={{ .Values.biometricmiddleware.url }}
            - --webhook.url={{ .Values.webhook.url }}
            - --webhook.app.key={{ .Values.webhook.app.key }}
            - --webhook.app.secret={{ .Values.webhook.app.secret }}
            - --redis.deployment=openshift
            - --redis.host=redis
            - --redis.port=6379
            - --server.connection-timeout=10m
            - --spring.servlet.multipart.max-file-size=50MB
            - --spring.servlet.multipart.max-request-size=50MB
            - --spring.servlet.multipart.enabled=true
            - --spring.http.multipart.max-file-size = 50MB
            - --spring.http.multipart.max-request-size = 50MB
            # - --mq.host=activemq
            - -Djava.security.egd=file:/dev/./urandom
            - --accounting.autopostjournal=true
            - --accounting.enable_costing=true
            - --doh.url=https://uhmistrn.doh.gov.ph/ahsr/webservice/index.php
            - --notification.provider={{ .Values.notification.provider }}
            - --notification.mercury.api={{ .Values.notification.mercury.api }}
            - --notification.mercury.app-key={{ .Values.notification.mercury.appKey }}
            - --notification.mercury.app-secret={{ .Values.notification.mercury.appSecret }}
            - --notification.patient-care={{ .Values.notification.patientCare }}
            - --notification.backoffice={{ .Values.notification.backoffice }}
            - --notification.inventory={{ .Values.notification.inventory }}
            - --notification.fixed-asset={{ .Values.notification.fixedAsset }}
            - --notification.hr-payroll={{ .Values.notification.hrPayroll }}
{{- end }}