apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      # ✅ Remove hostNetwork to avoid port conflict
      # hostNetwork: true
      # dnsPolicy: ClusterFirstWithHostNet

      # Image pull secrets if your registry requires auth
      imagePullSecrets:
        - name: {{ .Values.appName }}-secret

      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 4000
              protocol: TCP

          env:
            - name: TZ
              value: "Asia/Manila"
            - name: LANG
              value: "C"
            - name: LC_ALL
              value: "C"
            - name: DEVICE_IP
              value: "192.168.1.195"
            - name: DEVICE_PORT
              value: "4370"

          # Security context to allow ping inside container
          securityContext:
            capabilities:
              add:
                - NET_RAW

      
