singlenode: true
appName: atlas-samch

namespace: atlas-samch

image:
  name: acemcbmis/atlas
  tag: b9b69ff-dev

database:
  host: 10.104.0.7
  username: postgres
  password: af0cfc5db03a
  database: hismk2-samch


host:
  name: atlas-samch.hisd3.tech
  connect: connect.acemcbohol.dev


minio:
  url: s3.acemcbohol.dev
  accessKey: minioadmin
  secretKey: UkV6rc79adezx23
  bucketName: demo

storage:
  provider: NAS

hospitaltype:
  isgovernment: false


hospitalconfig:
  alias: "SAMCH"
