acemc: true
prod: true
appName: atlas-acemc

namespace: atlas-acemc

image:
  name: acemcbmis/atlas
  tag: 2e15df5-prod

database:
  host: 172.16.10.103
  port: 6432
  username: pgbouncer_pool
  password: d9ab8c4e4696
  database: hismk2-live
  hikari:
    maximumPoolSize: 40
    minimumIdle: 25
    registerMbeans: false

host:
  name: srv-hismk2.ace-mc-bohol.com
  connect: https://connect.ace-mc-bohol.com
  hermes: https://hermes.hisd3.tech

minio:
  url: s3.acemcbohol.dev
  accessKey: minioadmin
  secretKey: UkV6rc79adezx23
  bucketName: demo

doh:
  webService:
    key: ZFEN9zrRMyfSmH70QT5wlBeODhvAj326
    user: DOH37496
    password: e47200de8dd2221f

storage:
  provider: NAS

hospitalconfig:
  alias: ACEMCBH
  isgovernment: false
  coa:
    version: legacy

biometricmiddleware:
  url: 0.0.0.0

notification:
  provider: mercury
  mercury:
    api: https://notif.acemcbohol.dev
    appKey: 18716a8eea3296897a38f3240320d00a
    appSecret: 7987a5fc48a3381e8d4f688494a002d3
    disabled: true
  patientCare: https://patient-care.ace-mc.dev
  backoffice: https://bo.ace-mc-bohol.com
  inventory: https://inventory-v2.ace-mc-bohol.com
  fixedAsset: https://fixed-asset.ace-mc-bohol.com
  hrPayroll: https://hr.ace-mc-bohol.com

auth:
  username: scheduler
  password: YE%@&j-\\eB\\fv*2Y
