singlenode: true
appName: atlas-dianurse-demo

namespace: atlas-dianurse-demo

image:
  name: acemcbmis/atlas
  tag: b9b69ff-dev

database:
  host: 10.104.0.4
  username: postgres
  password: f3f@5bsd34$8910
  database: hismk2-dianurse-demo
  hikari:
    maximumPoolSize: 40
    minimumIdle: 25
    registerMbeans: false

hospitalconfig:
  alias: "DIANURSE"
  isgovernment: false
  coa:
    version: legacy

notification:
  provider: mercury
  mercury:
    api: https://notif.dianurse.com
    appKey: 18716a8eea3296897a38f3240320d00a
    appSecret: 7987a5fc48a3381e8d4f688494a002d3
    disabled: true
  patientCare: https://patient-care.dianurse.com
  backoffice: https://bo.dianurse.com
  inventory: https://inventory-v2.dianurse.com
  fixedAsset: https://fixed-asset.dianurse.com
  hrPayroll: https://hr.dianurse.com

  host:
    name: atlas.dianurse.com
    connect: https://connect.dianurse.dev

auth:
  username: system
  password: HCwm8qtz